# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

import os
import subprocess
import importlib
import math
import json
from pathlib import Path

import numpy as np

#
# Files listed from a known working invocation based on dataset/drivaer-sample.
#
EXPECTED_OUTPUT_FILES = {
    "ahmed-sample": [
        "test.manifest",
        "prediction/geometry-group-0-prediction.npy",
        "prediction/geometry-group-1-prediction.npy",
        "prediction/images/geometry-group-1-prediction-4.png",
        "prediction/images/geometry-group-0-prediction-5.png",
        "prediction/images/geometry-group-0-prediction-3.png",
        "prediction/images/geometry-group-1-combined-2.png",
        "prediction/images/geometry-group-0-error-4.png",
        "prediction/images/geometry-group-0-original-8.png",
        "prediction/images/geometry-group-1-original-8.png",
        "prediction/images/geometry-group-1-error-5.png",
        "prediction/images/geometry-group-0-error-2.png",
        "prediction/images/geometry-group-1-combined-4.png",
        "prediction/images/geometry-group-1-prediction-9.png",
        "prediction/images/geometry-group-0-combined-4.png",
        "prediction/images/geometry-group-1-original-3.png",
        "prediction/images/geometry-group-1-combined-3.png",
        "prediction/images/geometry-group-1-original-2.png",
        "prediction/images/geometry-group-0-error-8.png",
        "prediction/images/geometry-group-0-original-7.png",
        "prediction/images/geometry-group-1-error-3.png",
        "prediction/images/geometry-group-1-combined-6.png",
        "prediction/images/geometry-group-0-error-7.png",
        "prediction/images/geometry-group-1-error-9.png",
        "prediction/images/geometry-group-0-combined-6.png",
        "prediction/images/geometry-group-0-combined-0.png",
        "prediction/images/geometry-group-1-error-1.png",
        "prediction/images/geometry-group-0-combined-3.png",
        "prediction/images/geometry-group-1-error-6.png",
        "prediction/images/geometry-group-0-original-2.png",
        "prediction/images/geometry-group-0-prediction-0.png",
        "prediction/images/geometry-group-1-original-6.png",
        "prediction/images/geometry-group-1-combined-8.png",
        "prediction/images/geometry-group-1-original-1.png",
        "prediction/images/geometry-group-1-combined-9.png",
        "prediction/images/geometry-group-1-prediction-3.png",
        "prediction/images/geometry-group-0-prediction-2.png",
        "prediction/images/geometry-group-1-prediction-8.png",
        "prediction/images/geometry-group-0-original-1.png",
        "prediction/images/geometry-group-0-prediction-4.png",
        "prediction/images/geometry-group-0-combined-2.png",
        "prediction/images/geometry-group-0-original-3.png",
        "prediction/images/geometry-group-1-error-2.png",
        "prediction/images/geometry-group-0-error-0.png",
        "prediction/images/geometry-group-1-error-8.png",
        "prediction/images/geometry-group-0-error-5.png",
        "prediction/images/geometry-group-0-combined-9.png",
        "prediction/images/geometry-group-1-original-0.png",
        "prediction/images/geometry-group-1-prediction-7.png",
        "prediction/images/geometry-group-0-error-9.png",
        "prediction/images/geometry-group-0-combined-7.png",
        "prediction/images/geometry-group-1-combined-1.png",
        "prediction/images/geometry-group-0-error-6.png",
        "prediction/images/geometry-group-0-combined-1.png",
        "prediction/images/geometry-group-0-original-6.png",
        "prediction/images/geometry-group-0-prediction-9.png",
        "prediction/images/geometry-group-1-prediction-2.png",
        "prediction/images/geometry-group-1-error-7.png",
        "prediction/images/geometry-group-1-original-9.png",
        "prediction/images/geometry-group-0-original-4.png",
        "prediction/images/geometry-group-1-original-4.png",
        "prediction/images/geometry-group-1-prediction-6.png",
        "prediction/images/geometry-group-1-error-0.png",
        "prediction/images/geometry-group-1-prediction-0.png",
        "prediction/images/geometry-group-1-error-4.png",
        "prediction/images/geometry-group-0-prediction-1.png",
        "prediction/images/geometry-group-0-combined-5.png",
        "prediction/images/geometry-group-1-combined-7.png",
        "prediction/images/geometry-group-1-prediction-1.png",
        "prediction/images/geometry-group-0-original-5.png",
        "prediction/images/geometry-group-1-original-5.png",
        "prediction/images/geometry-group-1-combined-5.png",
        "prediction/images/geometry-group-0-prediction-6.png",
        "prediction/images/geometry-group-0-error-3.png",
        "prediction/images/geometry-group-0-prediction-7.png",
        "prediction/images/geometry-group-1-combined-0.png",
        "prediction/images/geometry-group-0-combined-8.png",
        "prediction/images/geometry-group-0-error-1.png",
        "prediction/images/geometry-group-0-original-9.png",
        "prediction/images/geometry-group-0-prediction-8.png",
        "prediction/images/geometry-group-1-prediction-5.png",
        "prediction/images/geometry-group-1-original-7.png",
        "prediction/images/geometry-group-0-original-0.png",
        "prediction/results.jsonl",
        ".project",
        "slices-copy.manifest",
        "validate.manifest",
        "train.manifest",
        "ae/training_output/last_model.pt",
        "ae/training_output/checkpoint_models/model_epoch0.pt",
        "ae/training_output/model_loss.csv",
        "ae/training_output/model_loss_log.png",
        "ae/training_output/best_model.pt",
        "ae/training_output/model_loss.png",
        "ae/inference_output/images/slice-group-2-combined-8.png",
        "ae/inference_output/images/slice-group-6-combined-1.png",
        "ae/inference_output/images/slice-group-4-original-5.png",
        "ae/inference_output/images/slice-group-2-combined-4.png",
        "ae/inference_output/images/slice-group-3-reconstructed-5.png",
        "ae/inference_output/images/slice-group-3-error-2.png",
        "ae/inference_output/images/slice-group-2-original-6.png",
        "ae/inference_output/images/slice-group-3-error-9.png",
        "ae/inference_output/images/slice-group-4-combined-4.png",
        "ae/inference_output/images/slice-group-2-error-7.png",
        "ae/inference_output/images/slice-group-3-combined-0.png",
        "ae/inference_output/images/slice-group-3-original-2.png",
        "ae/inference_output/images/slice-group-2-error-8.png",
        "ae/inference_output/images/slice-group-2-combined-3.png",
        "ae/inference_output/images/slice-group-6-reconstructed-9.png",
        "ae/inference_output/images/slice-group-4-original-7.png",
        "ae/inference_output/images/slice-group-3-reconstructed-2.png",
        "ae/inference_output/images/slice-group-3-original-6.png",
        "ae/inference_output/images/slice-group-6-original-1.png",
        "ae/inference_output/images/slice-group-4-reconstructed-1.png",
        "ae/inference_output/images/slice-group-6-reconstructed-5.png",
        "ae/inference_output/images/slice-group-3-reconstructed-1.png",
        "ae/inference_output/images/slice-group-6-error-0.png",
        "ae/inference_output/images/slice-group-4-original-8.png",
        "ae/inference_output/images/slice-group-2-combined-0.png",
        "ae/inference_output/images/slice-group-6-reconstructed-3.png",
        "ae/inference_output/images/slice-group-2-original-5.png",
        "ae/inference_output/images/slice-group-6-combined-9.png",
        "ae/inference_output/images/slice-group-2-error-1.png",
        "ae/inference_output/images/slice-group-2-original-9.png",
        "ae/inference_output/images/slice-group-3-error-7.png",
        "ae/inference_output/images/slice-group-2-error-4.png",
        "ae/inference_output/images/slice-group-2-combined-5.png",
        "ae/inference_output/images/slice-group-2-error-6.png",
        "ae/inference_output/images/slice-group-6-combined-2.png",
        "ae/inference_output/images/slice-group-3-original-3.png",
        "ae/inference_output/images/slice-group-6-original-9.png",
        "ae/inference_output/images/slice-group-6-reconstructed-1.png",
        "ae/inference_output/images/slice-group-4-error-9.png",
        "ae/inference_output/images/slice-group-4-combined-1.png",
        "ae/inference_output/images/slice-group-4-combined-2.png",
        "ae/inference_output/images/slice-group-6-error-9.png",
        "ae/inference_output/images/slice-group-2-reconstructed-8.png",
        "ae/inference_output/images/slice-group-6-combined-3.png",
        "ae/inference_output/images/slice-group-6-error-8.png",
        "ae/inference_output/images/slice-group-2-reconstructed-9.png",
        "ae/inference_output/images/slice-group-4-combined-0.png",
        "ae/inference_output/images/slice-group-6-reconstructed-7.png",
        "ae/inference_output/images/slice-group-2-reconstructed-2.png",
        "ae/inference_output/images/slice-group-4-original-0.png",
        "ae/inference_output/images/slice-group-3-combined-5.png",
        "ae/inference_output/images/slice-group-6-combined-4.png",
        "ae/inference_output/images/slice-group-2-combined-9.png",
        "ae/inference_output/images/slice-group-2-error-9.png",
        "ae/inference_output/images/slice-group-2-reconstructed-4.png",
        "ae/inference_output/images/slice-group-6-reconstructed-6.png",
        "ae/inference_output/images/slice-group-6-original-7.png",
        "ae/inference_output/images/slice-group-3-original-1.png",
        "ae/inference_output/images/slice-group-6-combined-0.png",
        "ae/inference_output/images/slice-group-4-reconstructed-6.png",
        "ae/inference_output/images/slice-group-6-combined-7.png",
        "ae/inference_output/images/slice-group-4-error-2.png",
        "ae/inference_output/images/slice-group-6-original-6.png",
        "ae/inference_output/images/slice-group-6-combined-8.png",
        "ae/inference_output/images/slice-group-3-reconstructed-8.png",
        "ae/inference_output/images/slice-group-3-error-1.png",
        "ae/inference_output/images/slice-group-3-original-5.png",
        "ae/inference_output/images/slice-group-6-error-7.png",
        "ae/inference_output/images/slice-group-3-combined-3.png",
        "ae/inference_output/images/slice-group-2-original-1.png",
        "ae/inference_output/images/slice-group-3-original-7.png",
        "ae/inference_output/images/slice-group-3-combined-8.png",
        "ae/inference_output/images/slice-group-4-combined-9.png",
        "ae/inference_output/images/slice-group-4-combined-6.png",
        "ae/inference_output/images/slice-group-3-original-8.png",
        "ae/inference_output/images/slice-group-6-reconstructed-0.png",
        "ae/inference_output/images/slice-group-4-reconstructed-3.png",
        "ae/inference_output/images/slice-group-3-combined-9.png",
        "ae/inference_output/images/slice-group-4-reconstructed-7.png",
        "ae/inference_output/images/slice-group-3-combined-2.png",
        "ae/inference_output/images/slice-group-3-original-9.png",
        "ae/inference_output/images/slice-group-4-reconstructed-5.png",
        "ae/inference_output/images/slice-group-4-original-1.png",
        "ae/inference_output/images/slice-group-6-reconstructed-2.png",
        "ae/inference_output/images/slice-group-4-original-6.png",
        "ae/inference_output/images/slice-group-2-original-4.png",
        "ae/inference_output/images/slice-group-2-reconstructed-0.png",
        "ae/inference_output/images/slice-group-2-original-2.png",
        "ae/inference_output/images/slice-group-6-original-0.png",
        "ae/inference_output/images/slice-group-4-reconstructed-9.png",
        "ae/inference_output/images/slice-group-3-original-4.png",
        "ae/inference_output/images/slice-group-3-error-8.png",
        "ae/inference_output/images/slice-group-2-error-3.png",
        "ae/inference_output/images/slice-group-4-combined-7.png",
        "ae/inference_output/images/slice-group-3-combined-4.png",
        "ae/inference_output/images/slice-group-2-error-2.png",
        "ae/inference_output/images/slice-group-6-original-4.png",
        "ae/inference_output/images/slice-group-6-original-3.png",
        "ae/inference_output/images/slice-group-2-original-3.png",
        "ae/inference_output/images/slice-group-6-original-2.png",
        "ae/inference_output/images/slice-group-2-reconstructed-7.png",
        "ae/inference_output/images/slice-group-4-combined-5.png",
        "ae/inference_output/images/slice-group-2-reconstructed-1.png",
        "ae/inference_output/images/slice-group-4-reconstructed-0.png",
        "ae/inference_output/images/slice-group-4-error-8.png",
        "ae/inference_output/images/slice-group-3-combined-7.png",
        "ae/inference_output/images/slice-group-4-error-5.png",
        "ae/inference_output/images/slice-group-4-reconstructed-8.png",
        "ae/inference_output/images/slice-group-6-error-5.png",
        "ae/inference_output/images/slice-group-3-combined-1.png",
        "ae/inference_output/images/slice-group-6-original-5.png",
        "ae/inference_output/images/slice-group-4-reconstructed-4.png",
        "ae/inference_output/images/slice-group-2-reconstructed-6.png",
        "ae/inference_output/images/slice-group-3-combined-6.png",
        "ae/inference_output/images/slice-group-4-error-4.png",
        "ae/inference_output/images/slice-group-4-reconstructed-2.png",
        "ae/inference_output/images/slice-group-3-error-5.png",
        "ae/inference_output/images/slice-group-4-original-2.png",
        "ae/inference_output/images/slice-group-4-combined-3.png",
        "ae/inference_output/images/slice-group-6-reconstructed-4.png",
        "ae/inference_output/images/slice-group-3-reconstructed-6.png",
        "ae/inference_output/images/slice-group-4-combined-8.png",
        "ae/inference_output/images/slice-group-4-error-1.png",
        "ae/inference_output/images/slice-group-6-combined-6.png",
        "ae/inference_output/images/slice-group-6-reconstructed-8.png",
        "ae/inference_output/images/slice-group-6-error-1.png",
        "ae/inference_output/images/slice-group-6-error-2.png",
        "ae/inference_output/images/slice-group-6-error-3.png",
        "ae/inference_output/images/slice-group-4-error-6.png",
        "ae/inference_output/images/slice-group-3-original-0.png",
        "ae/inference_output/images/slice-group-4-original-3.png",
        "ae/inference_output/images/slice-group-3-reconstructed-7.png",
        "ae/inference_output/images/slice-group-2-error-5.png",
        "ae/inference_output/images/slice-group-2-combined-6.png",
        "ae/inference_output/images/slice-group-2-combined-7.png",
        "ae/inference_output/images/slice-group-2-original-0.png",
        "ae/inference_output/images/slice-group-4-original-9.png",
        "ae/inference_output/images/slice-group-2-original-7.png",
        "ae/inference_output/images/slice-group-3-reconstructed-9.png",
        "ae/inference_output/images/slice-group-2-error-0.png",
        "ae/inference_output/images/slice-group-2-reconstructed-3.png",
        "ae/inference_output/images/slice-group-3-reconstructed-4.png",
        "ae/inference_output/images/slice-group-4-original-4.png",
        "ae/inference_output/images/slice-group-4-error-7.png",
        "ae/inference_output/images/slice-group-3-reconstructed-3.png",
        "ae/inference_output/images/slice-group-3-error-4.png",
        "ae/inference_output/images/slice-group-3-error-0.png",
        "ae/inference_output/images/slice-group-3-error-6.png",
        "ae/inference_output/images/slice-group-3-reconstructed-0.png",
        "ae/inference_output/images/slice-group-6-combined-5.png",
        "ae/inference_output/images/slice-group-3-error-3.png",
        "ae/inference_output/images/slice-group-6-error-6.png",
        "ae/inference_output/images/slice-group-6-error-4.png",
        "ae/inference_output/images/slice-group-4-error-3.png",
        "ae/inference_output/images/slice-group-2-reconstructed-5.png",
        "ae/inference_output/images/slice-group-2-combined-1.png",
        "ae/inference_output/images/slice-group-2-combined-2.png",
        "ae/inference_output/images/slice-group-6-original-8.png",
        "ae/inference_output/images/slice-group-2-original-8.png",
        "ae/inference_output/images/slice-group-4-error-0.png",
        "ae/inference_output/geometry-group-2.pt",
        "ae/inference_output/geometry-group-3.pt",
        "ae/inference_output/geometry-group-4.pt",
        "ae/inference_output/slice-group-6-reconstructed.pt",
        "ae/inference_output/slice-group-4-reconstructed.pt",
        "ae/inference_output/slice-group-3-reconstructed.pt",
        "ae/inference_output/results.jsonl",
        "ae/inference_output/geometry-group-5.pt",
        "ae/inference_output/geometry-group-6.pt",
        "ae/inference_output/slice-group-2-reconstructed.pt",
        "mgn/training_output/last_model.pt",
        "mgn/training_output/checkpoint_models/model_epoch0.pt",
        "mgn/training_output/model_loss.csv",
        "mgn/training_output/model_loss_log.png",
        "mgn/training_output/best_model.pt",
        "mgn/training_output/model_loss.png",
        "slices/slice-group-6.npy",
        "slices/slice-group-1.npy",
        "slices/slice-group-0.npy",
        "slices/slice-group-5.npy",
        "slices/slice-group-2.npy",
        "slices/slice-group-4.npy",
        "slices/slice-group-3.npy",
    ]
}


def test_slices(tmp_path):
    dataset_name = "ahmed-sample"
    dataset_path = importlib.resources.files("mlsimkit") / "datasets" / dataset_name
    manifest_path = str(dataset_path.joinpath("slices.manifest"))
    output_dir = str(tmp_path / "output")

    # fmt: off
    command = [
        "mlsimkit-learn", "--output-dir", f"{output_dir}",
        "slices",
        "preprocess",
            "--manifest-uri", manifest_path,
            "--manifest-base-relative-path", "PackageRoot",
            "--random-seed", str(42),
        "train-image-encoder",
            "--device", "cpu", # required with accelerate() to force test on cpu and one process
            "--training-output-dir", f"{output_dir}/ae/training_output",
            "--epochs", "10",
            "--batch-size", "1",
            "--mixed-precision", "fp16",
            "--deterministic",
            "--ae.input-channels", str(30),
            "--ae.img.width", str(128),
            "--ae.img.height", str(128),
            "--no-shuffle-data-each-epoch",
            "--no-add-noise-and-flip",
        "inspect-image-encoder",
        "process-mesh-data",
        "train-prediction",
            "--device", "cpu", # required with accelerate() to force test on cpu and one process
            "--training-output-dir", f"{output_dir}/mgn/training_output",
            "--epochs", "10",
            "--batch-size", "1",
            "--mixed-precision", "fp16",
            "--pooling-type", "max",
            "--deterministic",
        "predict",
            "--manifest-path", f"{output_dir}/test.manifest",
            "--mgn-model-path", f"{output_dir}/mgn/training_output/best_model.pt",
            "--ae-model-path", f"{output_dir}/ae/training_output/best_model.pt",  
            "--compare-groundtruth",
    ]
    # fmt: on

    subprocess.check_output(command)  # nosemgrep: dangerous-subprocess-use-audit

    # Check expected files as a smokecheck for now. At least we know the
    # commands run end-to-run...
    assert os.path.exists(output_dir)

    for file_path in EXPECTED_OUTPUT_FILES.get(dataset_name, ["FILE_DOES_NOT_EXIST"]):
        assert (Path(output_dir) / file_path).exists(), f"File {file_path} does not exist"

    # Check model performance stays the same.
    inference_metric_file_path = Path(output_dir) / "prediction" / "results.jsonl"

    with open(inference_metric_file_path, "r") as json_file:
        json_list = list(json_file)

    mses = []
    for json_str in json_list:
        result = json.loads(json_str)

    mses.append(result["metrics"]["mse"])

    # The expected_mse number needs to be adjusted when making changes that impact model performance.
    expected_mse = 0.009985589422285557
    assert math.isclose(np.mean(mses), expected_mse, abs_tol=1.5e-03)
