# KPI training configuration for Ahmed dataset
output-dir: outputs/training    # all artifacts output to CWD/output e,g models, images, metrics

log:
  prefix-dir: logs              # all logs go here
  config-file: logging.yaml     # tutorial-specific config

kpi:
  manifest_uri: training.manifest

  train:
    output_kpi_indices: "0"
    epochs: 100
    opt:
      learning_rate: 0.003

  predict:
    # Manifest includes labels, we want to evaluate performance
    compare-groundtruth: true
